# Generated by Django 4.1 on 2022-09-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_rating', models.IntegerField()),
                ('series_rating', models.IntegerField()),
                ('best_scene', models.CharField(max_length=1000)),
                ('worst_scene', models.CharField(max_length=1000)),
                ('favourite_actor', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=500)),
                ('season', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_series_rating', to='movie_api.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=500)),
                ('length', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_movie_rating', to='movie_api.rating')),
            ],
        ),
    ]
